### ISSUE TITLE
PlotWindow class declaration

### ISSUE THREAD

**Issue by eric-reeder** [eric-reeder/24780-project#3]
In your PlotWindow.h file, you never declare a PlotWindow class, but rather you declare two other classes. Each of these classes should be declared in their own .cpp and .h file pair, and you still need to create the actual PlotWindow class somewhere. Additionally, in the .cpp file, you are trying to include a header that doesn't exist.

**Comment by stephaniejennings** [comment]
I've fixed this and uploaded the files. I need to debug some more (they pass the compiler server) and add more comments, but the files are there.

**Comment by eric-reeder** [comment]
This actually still isn't fixed because the PlotWindow class doesn't exist. In your PlotWindow.h file, you still are declaring 2 classes (which you also shouldn't do because each header file should only contain one class declaration) and neither of them are a PlotWindow class. You need to create a class called PlotWindow that inherits from the GraphicsWindow class and that has, at a minimum, the functions that are called from the DynamicSystemApp

**Comment by stephaniejennings** [comment]
Ah, sorry about that! I'm still fuzzy on this concept, hence the confusion. But that explanation makes sense. I'll work on it this afternoon after you stop editing it.

**Comment by stephaniejennings** [comment]
Updated with GraphicsWindow inheritance
